fix the resotre cache issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -136,7 +136,7 @@ jobs:
       - checkout
       # Restore from cache
       - restore_cache:
-          key: backend-build
+          keys: [frontend-build]
       # Your job code here
       - run:
           name: test front-end
@@ -154,7 +154,7 @@ jobs:
       - checkout
       # Restore from cache
       - restore_cache:
-          key: backend-build
+          keys: [backend-build]
       # Your job code here
       - run:
           name: test front-end
@@ -172,7 +172,7 @@ jobs:
       - checkout
       # Restore from cache
       - restore_cache:
-          key: backend-build
+          keys: [frontend-build]
       # Your job code here
       - run:
           name: test front-end
@@ -191,6 +191,8 @@ jobs:
     steps:
       - checkout
       # Restore from cache
+      - restore_cache:
+          keys: [backend-build]
       # Your job code here
       - run:
           name: test front-end
@@ -293,8 +295,6 @@ jobs:
     steps:
       # Checkout code from git
       - checkout
-      - restore_cache:
-          key: backend-build
       - install_aws_cli
       - run:
           name: Run migrations
@@ -374,7 +374,7 @@ jobs:
           fingerprints:
             - "48:8e:2c:c4:5e:eb:e6:57:f4:2f:37:65:ae:f6:69:99"
       - restore_cache:
-          keys: [frontend-build]
+          keys: [backend-build]
       - run:
           name: Deploy backend
           command: |
@@ -397,10 +397,13 @@ jobs:
   smoke-test:
     docker:
       - image: cimg/base:stable
-      # Lightweight Docker image
+      
     steps:
       # Checkout code from git
       - checkout
+      - install_ansible_ubuntu
+      - install_aws_cli
+      - install_nodejs13
       - run:
           name: Install dependencies
           command: |
@@ -409,15 +412,40 @@ jobs:
           name: Get backend url
           command: |
             # your code here
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --output text)
+              # Fetch and prepare the BACKEND_IP env var
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                exit 0
+            else
+                exitf 1
+            fi
       - run:
           name: Backend smoke test.
           command: |
             # your code here
+
       - run:
           name: Frontend smoke test.
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure  
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              exit 1
+            else
+              exit 1
+            fi
+      # Here's where you will add some code to rollback on failure 
+      - destroy-environment
+      - revert-migrations
 
 #   cloudfront-update:
 #     docker:
